# Generated by Django 5.2.13 on 2026-04-22 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='クーポン名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('discount_type', models.CharField(choices=[('amount', '金額値引き'), ('percent', '割引率'), ('free', '無料')], max_length=20, verbose_name='割引種別')),
                ('discount_value', models.PositiveIntegerField(blank=True, help_text='金額値引きなら金額、割引率なら%を入力。無料の場合は空でOKです。', null=True, verbose_name='割引値')),
                ('start_at', models.DateTimeField(verbose_name='利用開始日時')),
                ('end_at', models.DateTimeField(verbose_name='利用終了日時')),
                ('usage_note', models.TextField(blank=True, verbose_name='利用条件メモ')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開状態')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効状態')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_coupons', to=settings.AUTH_USER_MODEL, verbose_name='店舗ユーザー')),
            ],
            options={
                'verbose_name': '通常クーポン',
                'verbose_name_plural': '通常クーポン',
                'ordering': ['-created_at'],
            },
        ),
    ]
