# Generated by Django 5.2.13 on 2026-04-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customeremailotp_customeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='google_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
