# Generated by Django 5.2.13 on 2026-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_storeuser_line_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='google_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
