# Generated by Django 5.2.13 on 2026-04-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customeruser_google_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
