# Generated by Django 5.2.13 on 2026-04-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customeruser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
