# Generated by Django 5.2.13 on 2026-04-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customeruser_deleted_at_customeruser_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='store_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
