# Generated by Django 5.2.13 on 2026-04-12 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StampCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='カード名')),
                ('required_stamps', models.PositiveIntegerField(verbose_name='必要スタンプ数')),
                ('reward_name', models.CharField(max_length=100, verbose_name='特典名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'スタンプカード',
                'verbose_name_plural': 'スタンプカード',
                'ordering': ['-created_at'],
            },
        ),
    ]
