# Generated by Django 5.2.13 on 2026-04-13 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customeremailotp_customeruser'),
        ('stampcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StampGrantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_count', models.PositiveIntegerField(default=1)),
                ('qr_payload', models.TextField(blank=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_grant_logs', to='accounts.customeruser')),
                ('stamp_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_grant_logs', to='stampcards.stampcard')),
                ('store_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_grant_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerStampCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stamps', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_stamp_cards', to='accounts.customeruser')),
                ('stamp_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_stamp_cards', to='stampcards.stampcard')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('customer', 'stamp_card')},
            },
        ),
    ]
