# Generated by Django 5.2.13 on 2026-04-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customeremailotp_customeruser'),
        ('stampcards', '0002_stampgrantlog_customerstampcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('available', '利用可能'), ('used', '使用済み')], default='available', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_coupons', to='accounts.customeruser')),
                ('stamp_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_coupons', to='stampcards.stampcard')),
            ],
        ),
    ]
